[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
] #this means when our contract see the link @chainlink/contracts/, it should refer to lib/chainlink-brownie-contracts/contracts/ folder 

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
